function Inversiones() {
  return (
    <section id="inversiones" className='padded'>
      <div className="container">
        <h2>Inversiones</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga dolores quod soluta aliquid dolor quis libero, quasi, ab corrupti voluptatibus non harum odit dolorum, ad veritatis culpa autem optio labore maxime eveniet tenetur debitis expedita. Temporibus neque vero facere quaerat enim accusamus sed ab repudiandae. Ipsa ex officiis ducimus pariatur a similique, perspiciatis corrupti error repudiandae exercitationem, voluptates provident hic distinctio quidem quisquam tenetur illum! Minima non, vero itaque adipisci ratione sequi eveniet tenetur nisi quibusdam, natus numquam impedit magni ea facilis! Tempora facilis ex omnis voluptatibus labore ducimus tempore fuga neque non cumque voluptatem deserunt esse, minima iste consequuntur?</p>
        <p>Reprehenderit consectetur nesciunt est sequi officia omnis aliquam laboriosam sed sapiente! Nemo omnis ipsum facere ullam non esse, dicta ratione atque quisquam aperiam quae autem, nesciunt repudiandae aliquam a quibusdam voluptatum et ut quis fugit vero fugiat rerum voluptatibus? Eos maxime vel, ut assumenda aliquam libero dolore tenetur maiores facere voluptate velit, esse minima autem ipsum voluptas eaque minus nihil, quas officia! Magnam, nobis itaque modi animi exercitationem, deserunt in sit adipisci corrupti libero aspernatur ab quaerat voluptate vero dolores culpa iure. Numquam officia magni vitae omnis cupiditate quaerat, explicabo quam laudantium impedit, sint iusto aliquid beatae? Non, vero ut!</p>
        <p>Quasi hic rem doloribus, possimus rerum excepturi quisquam repudiandae dolore suscipit quod expedita veniam, distinctio nisi? Vero repudiandae eveniet repellendus doloribus quibusdam illo quis alias corrupti. Sapiente quo nesciunt rerum porro maxime, soluta minima provident harum ducimus veritatis eius ab fugiat necessitatibus corrupti. Neque, totam? Vero, veniam aut! Obcaecati rerum deleniti non repudiandae ipsam at reprehenderit amet dicta voluptatibus in pariatur tempora, sit incidunt, cumque placeat! Nobis dolore quod, temporibus asperiores in impedit voluptates nisi porro aut ipsa sed, facilis illum distinctio voluptatibus perferendis, deleniti expedita velit rerum corporis maiores voluptas culpa. Maiores facere ad eum fugit in libero quae.</p>
        <p>Dolorem obcaecati, consectetur quisquam sunt iste maxime itaque deleniti amet fugiat odit placeat voluptate non repellendus necessitatibus vel nesciunt praesentium numquam molestiae cupiditate quos explicabo a iure quidem sed! Deleniti, error molestiae! Ea dolorum animi nobis recusandae! Laborum, eum! Sed adipisci nobis nisi non ad doloremque minima rem laborum iusto blanditiis aspernatur ipsum saepe numquam dolore, quia, cumque tempora magni eveniet asperiores libero optio. Officiis labore fugiat ullam voluptates, perspiciatis accusamus veniam reprehenderit impedit animi repellat repudiandae ipsum? In distinctio neque deleniti totam! Totam tempora omnis provident neque impedit quos sequi, fuga rerum sit aperiam doloribus? Quisquam voluptatibus assumenda totam!</p>
        <p>Corporis repellat sapiente amet dignissimos magnam? Et ipsam impedit minima a? Rem ut molestias officia voluptas libero asperiores corporis soluta alias molestiae nam laudantium, ullam tenetur ducimus tempora aliquid eligendi facere, deleniti assumenda pariatur voluptate! Reiciendis, obcaecati modi quos enim dolore quam excepturi cumque ea doloremque sequi laborum ducimus perferendis quaerat, nihil est natus praesentium iusto vero veniam nulla repudiandae deleniti dolores! Aliquid perferendis rem nostrum debitis. Omnis consequuntur hic odio nisi! Est quo a obcaecati, minus provident excepturi ipsam enim beatae laborum. Quas assumenda quasi laborum a, sit nihil quod quia, facilis, iusto amet placeat laboriosam consequuntur fugiat labore?</p>
      </div>
    </section>
  )
}

export default Inversiones
